core/routes/web.php
    Route::post('razorpay', 'razorpay\ProcessController@ipn')->name('razorpay');
    Route::post('instamojo', 'instamojo\ProcessController@ipn')->name('instamojo');
    Route::get('blockchain', 'blockchain\ProcessController@ipn')->name('blockchain');
    Route::get('blockio', 'blockio\ProcessController@ipn')->name('blockio');
    Route::post('coinpayments', 'coinpayments\ProcessController@ipn')->name('coinpayments');
    Route::post('coinpayments_fiat', 'coinpayments_fiat\ProcessController@ipn')->name('coinpayments_fiat');
    Route::post('coingate', 'coingate\ProcessController@ipn')->name('coingate');
    Route::post('coinbase_commerce', 'coinbase_commerce\ProcessController@ipn')->name('coinbase_commerce');
    Route::get('mollie', 'mollie\ProcessController@ipn')->name('mollie');
    Route::post('cashmaal', 'cashmaal\ProcessController@ipn')->name('cashmaal');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetLinkEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify-code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.change-link');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin'])->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');


        
        // Users Manager
        Route::get('user/email/{id}/{flag}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}/{role}', 'ManageUsersController@sendEmailSingle')->name('users.send.email.single');
       
        Route::get('advertiser/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('publisher/transactions/{id}', 'ManageUsersController@publisherTransactions')->name('publisher.transactions');
        Route::get('advertiser/deposits/{id}', 'ManageUsersController@deposits')->name('users.deposits');
        Route::get('publisher/withdrawals/{id}', 'ManageUsersController@withdrawals')->name('users.withdrawals');
       
        // Login History
        Route::get('users/login/ipHistory/{ip}', 'ReportController@loginIpHistory')->name('users.login.ipHistory');
        Route::get('report/login/history', 'ReportController@loginHistory')->name('report.login.history');

        // Report
        Route::get('report/publishers/earning-logs', 'ReportController@publisherEarningLogs')->name('earnings.publisher');
        Route::get('report/transaction/advertisers', 'ReportController@advertiserTransaction')->name('transaction.advertiser');


         //Advertises
         Route::get('/advertise/all', 'AdvertiseController@allAdvertise')->name('advertise.all');
         Route::get('/advertise/details/{id}', 'AdvertiseController@advertiseDetails')->name('advertise.details');
         Route::get('/advertise/cpc&cpm/', 'AdvertiseController@perCost')->name('advertise.perCost');
         Route::post('/advertise/cpc&cpm/update', 'AdvertiseController@perCostUpdate')->name('advertise.perCost.update');
          #price-plan
         Route::get('/advertise/price-plan', 'AdvertiseController@pricePlan')->name('advertise.price-plan');
         Route::post('/advertise/add/price-plan', 'AdvertiseController@addPricePlan')->name('advertise.add.price-plan');
         Route::post('/advertise/update/price-plan/{id}', 'AdvertiseController@updatePricePlan')->name('advertise.update.price-plan');
         Route::post('/advertise/price-plan/remove/{id}', 'AdvertiseController@removePricePlan')->name('advertise.priceplan.remove');
          #type
         Route::get('/advertise/type', 'AdvertiseController@type')->name('advertise.type');
         Route::post('/advertise/add/type', 'AdvertiseController@addType')->name('advertise.add.type');
         Route::post('/advertise/update/type/{id}', 'AdvertiseController@updateType')->name('advertise.update.type');
         Route::post('/advertise/update/{id}', 'AdvertiseController@updateAd')->name('advertise.update');

         Route::get('/advertise/ip-log', 'AdvertiseController@ipLog')->name('advertise.iplog');
         Route::get('/advertise/blocked/ip-log', 'AdvertiseController@blockedIpLog')->name('advertise.blockedip');
         Route::post('/advertise/ip/block/{id}', 'AdvertiseController@blockIp')->name('advertise.ip.block');
         Route::post('/advertise/ip/unblock/{id}', 'AdvertiseController@unBlockIp')->name('advertise.ip.unblock');
 
         // keywords
         Route::get('keywords', 'AdvertiseController@keywords')->name('keywords');
         Route::post('add/keywords', 'AdvertiseController@addKeyword')->name('add.keywords');
         Route::post('update/keyword/{id}', 'AdvertiseController@upateKeyword')->name('update.keywords');
         Route::post('remove/keyword/{id}', 'AdvertiseController@removeKeyword')->name('remove.keyword');
 
         //Manage Advertiser
         Route::get('/advertiser/all','AdvertiserController@allAdvertiser')->name('advertiser.all');
         Route::get('/advertiser/active/all','AdvertiserController@allActiveAdvertiser')->name('advertiser.active.all');
         Route::get('/advertiser/details/{id}','AdvertiserController@advertiserDetails')->name('advertiser.details');
         Route::post('/advertiser/update/{id}','AdvertiserController@advertiserUpdate')->name('advertiser.update');
         Route::post('/advertiser/ads/details/{id}','AdvertiserController@advertiserAdsDetails')->name('advertiser.ads.details');
         Route::post('advertiser/add-sub-balance/{id}', 'AdvertiserController@addSubBalance')->name('advertiser.addSubBalance');
         Route::get('/advertiser/banned/all','AdvertiserController@allBannedAdvertiser')->name('advertiser.banned.all');
         Route::get('/advertiser/banned/{id}','AdvertiserController@advertiserBanned')->name('advertiser.banned');
         Route::get('/advertiser/active/{id}','AdvertiserController@advertiserActive')->name('advertiser.active');
         Route::get('/advertiser/email-unverified','AdvertiserController@emailUnverified')->name('advertiser.email.unverified');
         Route::get('/advertiser/sms-unverified','AdvertiserController@smsUnverified')->name('advertiser.sms.unverified');
 
         Route::get('advertiser/login/history/{id}', 'AdvertiserController@loginHistory')->name('advertiser.login.history.single');
         Route::get('advertiser/ads/{id}', 'AdvertiserController@advertiserAds')->name('advertiser.ads');
        
         Route::get('advertiser/send-email', 'AdvertiserController@showEmailAllForm')->name('advertiser.email.all');
         Route::post('advertiser/send-email', 'AdvertiserController@sendEmailAll')->name('advertiser.email.send');
         Route::get('advertiser/search', 'AdvertiserController@search')->name('advertiser.search');
 
         
         //Manage publisher
         Route::get('/publisher/all','PublisherController@allPublisher')->name('publisher.all');
         Route::get('/publisher/active/all','PublisherController@allActivePublisher')->name('publisher.active.all');
         Route::get('/publisher/details/{id}','PublisherController@publisherDetails')->name('publisher.details');
         Route::post('/publisher/update/{id}','PublisherController@publisherUpdate')->name('publisher.update');
         Route::get('/publisher/banned/all','PublisherController@allBannedPublisher')->name('publisher.banned.all');
         Route::get('/publisher/banned/{id}','PublisherController@publisherBanned')->name('publisher.banned');
         Route::get('/publisher/active/{id}','PublisherController@publisherActive')->name('publisher.active');
         Route::get('/publisher/email-unverified','PublisherController@emailUnverified')->name('publisher.email.unverified');
         Route::get('/publisher/sms-unverified','PublisherController@smsUnverified')->name('publisher.sms.unverified');
 
         Route::post('/publisher/ads/{slug}/{id}','PublisherController@publisherAds')->name('publisher.ads');
         Route::post('/publisher/ads/details/{id}','PublisherController@publisherAdsDetails')->name('publisher.ads.details');
         Route::post('publisher/add-sub-balance/{id}', 'PublisherController@addSubBalance')->name('publisher.addSubBalance');

core/resources/views/admin/advertises/allAdvertises.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row">
        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Ad Name')</th>
                                <th scope="col">@lang('Ad title')</th>
                                <th scope="col">@lang('Type')</th>
                                <th scope="col">@lang('Advertiser')</th>
                                <th scope="col">@lang('Impression')</th>
                                <th scope="col">@lang('Click')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($advertises as $advertise)
                            
                            <tr>
                                <td data-label="@lang('Ad Name')" class="text--primary">{{ $advertise->ad_name }}</td>
                                <td data-label="@lang('Ad title')" class="text--primary">{{ $advertise->ad_title }}</td>
                                <td data-label="@lang('Type')"><span class="text--small badge font-weight-normal {{$advertise->ad_type=='click'?'badge--primary':'badge--warning'}} ">{{ $advertise->ad_type }}</span></td>
                                <td data-label="@lang('Advertiser')"><a href="{{route('admin.advertiser.details',$advertise->advertiser->id)}}">{{ $advertise->advertiser->name }}</a></td>
                                
                                <td data-label="@lang('Impression')">{{$advertise->impression??'0'}}</td>
                              
                                <td data-label="@lang('Click')">{{$advertise->clicked??'0'}}</td>
                               
                                @if ($advertise->status)
                                <td data-label="@lang('Status')"><span class="text--small badge font-weight-normal badge--success">@lang('Active')</span></td>
                                @else
                                <td data-label="@lang('Status')"><span class="text--small badge font-weight-normal badge--warning">@lang('Deactive')</span></td>
                                @endif
                                <td data-label="@lang('Action')">
                                    <a href="{{ route('admin.advertise.details',$advertise->id) }}" class="icon-btn" data-toggle="tooltip" title="@lang('details')">
                                        <i class="las la-desktop text--shadow"></i>
                                    </a>
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{$advertises->links('admin.partials.paginate')}}
                </div>
            </div><!-- card end -->
        </div>


    </div>
@endsection

core/resources/views/admin/advertises/details.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="row mb-none-30">

        <div class="col-xl-12 col-lg-12 col-md-12 mb-30">
            <div class="row mb-none-30">
                <div class="col-xl-4 col-lg-6 col-sm-6 mb-30">
                    <div class="dashboard-w1 bg--gradi-9 b-radius--10 box-shadow has--link">
                        <a href="javascript:void(0)" class="item--link"></a>
                        <div class="icon">
                            <i class="las la-hand-point-up"></i>
                        </div>
                        <div class="details">
                            <div class="numbers">
                                <span class="amount">{{ $advertise->clicked ?  $advertise->clicked : 0}}</span>
                            </div>
                            <div class="desciption">
                                <span>@lang('Total Clicked')</span>
                            </div>
                        </div>
                    </div>
                </div><!-- dashboard-w1 end -->
                <div class="col-xl-4 col-lg-6 col-sm-6 mb-30">
                    <div class="dashboard-w1 bg--gradi-1 b-radius--10 box-shadow has--link">
                        <a href="javascript:void(0)" class="item--link"></a>
                        <div class="icon">
                             <i class="las la-globe"></i>
                        </div>
                        <div class="details">
                            <div class="numbers">
                                <span class="amount">{{ $advertise->impression ? $advertise->impression:0}}</span>
                            </div>
                            <div class="desciption">
                                <span>@lang('Total Impression')</span>
                            </div>
                        </div>
                    </div>
                </div><!-- dashboard-w1 end -->

                <div class="col-xl-4 col-lg-6 col-sm-6 mb-30">
                    <div class="dashboard-w1 bg--gradi-13 b-radius--10 box-shadow has--link">
                        <a href="javascript:void(0)" class="item--link"></a>
                        <div class="icon">
                             <i class="las la-hand-point-up"></i>
                        </div>
                        <div class="details">
                            <div class="numbers">
                                <span class="amount">{{ ucfirst($advertise->ad_type)}}</span>
                            </div>
                            <div class="desciption">
                                <span>@lang('Ad Type')</span>
                            </div>
                        </div>
                    </div>
                </div><!-- dashboard-w1 end -->
            </div>

            <form action="{{route('admin.advertise.update',$advertise->id)}}" method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-xl-7 col-lg-12">
                    <div class="card mt-25">
                        <div class="card-body">
                            <h5 class="card-title mb-15 border-bottom pb-2">{{$advertise->name}} @lang('Information')</h5>

                                @csrf

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group ">
                                            <label class="form-control-label font-weight-bold">@lang('Advertiser')</label>
                                            <input class="form-control" type="text" value="{{$advertise->advertiser->name}}" disabled>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group ">
                                            <label class="form-control-label font-weight-bold">@lang('Name')<span class="text-danger">*</span></label>
                                            <input class="form-control" type="text" name="name"  value="{{$advertise->ad_name}}" disabled>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group ">
                                            <label class="form-control-label font-weight-bold">@lang('Redirect Url ')<span
                                                    class="text-danger">*</span></label>
                                            <input class="form-control" type="text" name="url" value="{{$advertise->redirect_url}}">
                                        </div>
                                    </div>
                                </div>
                                @if($advertise->keywords!=null)
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group ">
                                            <label class="font-weight-bold" for="">@lang('Keywords')<span class="text-danger">*</span></label>
                                            <select name="keywords[]"  class="form-control select2-auto-tokenize" data-keyword="{{json_encode(@$advertise->keywords)}}" id="keyword" multiple="multiple">
                                                @foreach (@$advertise->keywords as $keyword)
                                                <option value="{{$keyword}}" selected>{{$keyword}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                @endif
                                @if($advertise->t_country!=null)
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group ">
                                            <label class="font-weight-bold" for="exampleInputPassword1">@lang('Targeted Country')<span class="text-danger">*</span></label>
                                            <select name="country[]"  class="form-control select2-auto-tokenize" id="country" data-country="{{json_encode($advertise->t_country)}}" multiple="multiple" placeholder="Select your targeted country">
                                                @foreach (@$advertise->t_country as $country)
                                                <option value="{{$country}}" selected>{{$country}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                @endif
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="custom-control custom-checkbox form-check-primary my-2">
                                            <input type="checkbox" name="global" class="custom-control-input global"
                                                   {{$advertise->global==1?'checked':''}} id="customCheck21">
                                            <label class="custom-control-label font-weight-bold"
                                                   for="customCheck21">@lang('Target for global')</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-xl-12 col-md-6  col-sm-3 col-12">
                                        <label class="form-control-label font-weight-bold">@lang('Status') </label>
                                        <input type="checkbox" data-width="100%" data-onstyle="-success" data-offstyle="-danger"
                                        data-toggle="toggle" data-on="Active" data-off="Inactive" data-width="100%"
                                        name="status"
                                        @if($advertise->status == 1 ) checked @endif>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>

            <div class="col-xl-5 col-lg-12">
                <div class="card b-radius--10 overflow-hidden box--shadow1 mt-4 d-inline-block">
                    <div class="card-body p-0">
                        <div class="p-3 bg--white">
                            <div><img src="{{getImage('assets/images/adImage/'. @$advertise->image) }}" width="{{  @$advertise->type->width }}" height="{{  @$advertise->type->height }}"/></div>
                            <div class="mt-15">
                                <h4 class="">{{@$advertise->ad_name}} <small class="text-danger">({{ @$advertise->resolution }})@lang('px') </small></h4>
                                <span class="text--small">@lang('Created At ')<strong>{{date('d M, Y h:i A',strtotime(@$advertise->created_at))}} </strong></span>
                            </div>
                        </div>
                    </div>
                </div>
          </div>
        </div>

        <div class="row mt-4">
            <div class="col-md-12">
                <div class="form-group">
                    <button type="submit" class="btn btn--primary btn-block btn-lg">@lang('Save Changes')
                    </button>
                </div>
            </div>
          </div>
        </form>
        </div>
    </div>


@endsection

@push('breadcrumb-plugins')
<a href="{{ route('admin.advertise.all') }}" class="btn btn--primary"><i class="las la-backward"></i> @lang('Go Back')</a>

@endpush


@push('style')
    <style>
        .ad-image img{
            height: 280px;
        }
    </style>

@endpush


@push('script')
    <script>
       'use strict';
            (function ($) {
                var country = $('#country').data('country');
                var url = "{{route('countries')}}";
                $.get(url,function(result,state){
                    result = result.filter(val => !country.includes(val));
                result.forEach(function (cn) {
                $('#country').append('<option value="'+cn+'">'+cn+'</option>')
                });
                })

                var keyword = $('#keyword').data('keyword')
                var keywordUrl = "{{route('keywords')}}";

                $.get(keywordUrl,function(result){
                    result = result.filter(val => !keyword.includes(val));
                    result.forEach(function (cn) {
                    $('#keyword').append('<option value="'+cn+'">'+cn+'</option>')
                    });
                })

                if($(".global").is(':checked'))
                   $("#country").attr('disabled',true);  // checked
                else
                    $("#country").attr('disabled',false);

                    $(".global").on('change',function(){
                       if( $(this).is(':checked')){
                         $("#country").attr('disabled',true); 
                       } else{
                        $("#country").attr('disabled',false); 
                       }
                    })
            })(jQuery);

    </script>
@endpush

core/resources/views/admin/advertises/ip_logs.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row">

        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Ip')</th>
                                <th scope="col">@lang('Advertise')</th>
                                <th scope="col">@lang('Ad Type')</th>
                                <th scope="col">@lang('Country')</th>
                                <th scope="col">@lang('Time')</th>
                                <th scope="col">@lang('Date')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($logs as $log)
                               
                                <tr>
                                    <td data-label="@lang('Ip')">{{$log->ip->ip}}</td>
                                    <td data-label="@lang('Advertise')"><a href="{{route('admin.advertise.details',$log->ad_id)}}">{{$log->ad->ad_title}}</a></td>
                                    <td data-label="@lang('Ad Type')">{{$log->ad_type}}</td>
                                    <td data-label="@lang('Country')"><span class="text--small badge font-weight-normal badge--primary">{{$log->country}}</span></td>
                                    <td data-label="@lang('Time')">{{\Carbon\Carbon::parse($log->time)->format('g:i A')}}</td>
                                    <td data-label="@lang('Date')">{{showDateTime($log->created_at,'d M Y')}}</td>
                                    <td data-label="@lang('Action')">
                                        <a href="javascript:void(0)" data-route="{{route('admin.advertise.ip.block',$log->ip->id)}}" class="icon-btn btn--danger block" data-toggle="tooltip" title="@lang('Block IP')">
                                            <i class="las la-ban text--shadow"></i>
                                        </a>
                                    </td>
                                </tr>
                            
                           
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{paginateLinks($logs)}}
                </div>
            </div><!-- card end -->
        </div>

        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
               <button type="button" class="close ml-auto m-3" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>
                    <form action="" method="POST">
                        @csrf
                        <div class="modal-body text-center">
                            
                            <i class="las la-exclamation-circle text-danger display-2 mb-15"></i>
                            <h4 class="text--secondary mb-15">@lang('Are You Sure Want to Block This Ip?')</h4>
    
                        </div>
                    <div class="modal-footer justify-content-center">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">@lang('close')</button>
                      <button type="submit"  class="btn btn-danger del">@lang('Block')</button>
                    </div>
                    
                    </form>
              </div>
            </div>
        </div>

    </div>
@endsection

@push('script')

<script>
    'use strict';
    $('.block').on('click',function(){
        var route = $(this).data('route')
        var modal = $('#deleteModal');
        modal.find('form').attr('action',route)
        modal.modal('show');


    })
</script>

@endpush

@push('breadcrumb-plugins')
    <form action="" method="GET" class="form-inline float-sm-right bg--white">
        <div class="input-group has_append">
            <input type="text" name="search" class="form-control" placeholder="@lang('Ip')" value="{{$search??''}}" autocomplete="off">
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>    
@endpush