core/routes/web.php
    Route::post('instamojo', 'instamojo\ProcessController@ipn')->name('instamojo');
    Route::get('blockchain', 'blockchain\ProcessController@ipn')->name('blockchain');
    Route::get('blockio', 'blockio\ProcessController@ipn')->name('blockio');
    Route::post('coinpayments', 'coinpayments\ProcessController@ipn')->name('coinpayments');
    Route::post('coinpayments_fiat', 'coinpayments_fiat\ProcessController@ipn')->name('coinpayments_fiat');
    Route::post('coingate', 'coingate\ProcessController@ipn')->name('coingate');
    Route::post('coinbase_commerce', 'coinbase_commerce\ProcessController@ipn')->name('coinbase_commerce');
    Route::get('mollie', 'mollie\ProcessController@ipn')->name('mollie');
    Route::post('cashmaal', 'cashmaal\ProcessController@ipn')->name('cashmaal');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetLinkEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify-code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.change-link');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin'])->group(function () {
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');


        
        // Users Manager
        Route::get('user/email/{id}/{flag}', 'ManageUsersController@showEmailSingleForm')->name('users.email.single');
        Route::post('user/send-email/{id}/{role}', 'ManageUsersController@sendEmailSingle')->name('users.send.email.single');
       
        Route::get('advertiser/transactions/{id}', 'ManageUsersController@transactions')->name('users.transactions');
        Route::get('publisher/transactions/{id}', 'ManageUsersController@publisherTransactions')->name('publisher.transactions');
        Route::get('advertiser/deposits/{id}', 'ManageUsersController@deposits')->name('users.deposits');
        Route::get('publisher/withdrawals/{id}', 'ManageUsersController@withdrawals')->name('users.withdrawals');
       
        // Login History
        Route::get('users/login/ipHistory/{ip}', 'ReportController@loginIpHistory')->name('users.login.ipHistory');
        Route::get('report/login/history', 'ReportController@loginHistory')->name('report.login.history');

        // Report
        Route::get('report/publishers/earning-logs', 'ReportController@publisherEarningLogs')->name('earnings.publisher');
        Route::get('report/transaction/advertisers', 'ReportController@advertiserTransaction')->name('transaction.advertiser');


         //Advertises
         Route::get('/advertise/all', 'AdvertiseController@allAdvertise')->name('advertise.all');
         Route::get('/advertise/details/{id}', 'AdvertiseController@advertiseDetails')->name('advertise.details');
         Route::get('/advertise/cpc&cpm/', 'AdvertiseController@perCost')->name('advertise.perCost');
         Route::post('/advertise/cpc&cpm/update', 'AdvertiseController@perCostUpdate')->name('advertise.perCost.update');
          #price-plan
         Route::get('/advertise/price-plan', 'AdvertiseController@pricePlan')->name('advertise.price-plan');
         Route::post('/advertise/add/price-plan', 'AdvertiseController@addPricePlan')->name('advertise.add.price-plan');
         Route::post('/advertise/update/price-plan/{id}', 'AdvertiseController@updatePricePlan')->name('advertise.update.price-plan');
         Route::post('/advertise/price-plan/remove/{id}', 'AdvertiseController@removePricePlan')->name('advertise.priceplan.remove');
          #type
         Route::get('/advertise/type', 'AdvertiseController@type')->name('advertise.type');
         Route::post('/advertise/add/type', 'AdvertiseController@addType')->name('advertise.add.type');
         Route::post('/advertise/update/type/{id}', 'AdvertiseController@updateType')->name('advertise.update.type');
         Route::post('/advertise/update/{id}', 'AdvertiseController@updateAd')->name('advertise.update');

         Route::get('/advertise/ip-log', 'AdvertiseController@ipLog')->name('advertise.iplog');
         Route::get('/advertise/blocked/ip-log', 'AdvertiseController@blockedIpLog')->name('advertise.blockedip');
         Route::post('/advertise/ip/block/{id}', 'AdvertiseController@blockIp')->name('advertise.ip.block');
         Route::post('/advertise/ip/unblock/{id}', 'AdvertiseController@unBlockIp')->name('advertise.ip.unblock');
 
         // keywords
         Route::get('keywords', 'AdvertiseController@keywords')->name('keywords');
         Route::post('add/keywords', 'AdvertiseController@addKeyword')->name('add.keywords');
         Route::post('update/keyword/{id}', 'AdvertiseController@upateKeyword')->name('update.keywords');
         Route::post('remove/keyword/{id}', 'AdvertiseController@removeKeyword')->name('remove.keyword');
 
         //Manage Advertiser
         Route::get('/advertiser/all','AdvertiserController@allAdvertiser')->name('advertiser.all');
         Route::get('/advertiser/active/all','AdvertiserController@allActiveAdvertiser')->name('advertiser.active.all');
         Route::get('/advertiser/details/{id}','AdvertiserController@advertiserDetails')->name('advertiser.details');
         Route::post('/advertiser/update/{id}','AdvertiserController@advertiserUpdate')->name('advertiser.update');
         Route::post('/advertiser/ads/details/{id}','AdvertiserController@advertiserAdsDetails')->name('advertiser.ads.details');
         Route::post('advertiser/add-sub-balance/{id}', 'AdvertiserController@addSubBalance')->name('advertiser.addSubBalance');
         Route::get('/advertiser/banned/all','AdvertiserController@allBannedAdvertiser')->name('advertiser.banned.all');
         Route::get('/advertiser/banned/{id}','AdvertiserController@advertiserBanned')->name('advertiser.banned');
         Route::get('/advertiser/active/{id}','AdvertiserController@advertiserActive')->name('advertiser.active');
         Route::get('/advertiser/email-unverified','AdvertiserController@emailUnverified')->name('advertiser.email.unverified');
         Route::get('/advertiser/sms-unverified','AdvertiserController@smsUnverified')->name('advertiser.sms.unverified');
 
         Route::get('advertiser/login/history/{id}', 'AdvertiserController@loginHistory')->name('advertiser.login.history.single');
         Route::get('advertiser/ads/{id}', 'AdvertiserController@advertiserAds')->name('advertiser.ads');
        
         Route::get('advertiser/send-email', 'AdvertiserController@showEmailAllForm')->name('advertiser.email.all');
         Route::post('advertiser/send-email', 'AdvertiserController@sendEmailAll')->name('advertiser.email.send');
         Route::get('advertiser/search', 'AdvertiserController@search')->name('advertiser.search');
 
         
         //Manage publisher
         Route::get('/publisher/all','PublisherController@allPublisher')->name('publisher.all');
         Route::get('/publisher/active/all','PublisherController@allActivePublisher')->name('publisher.active.all');
         Route::get('/publisher/details/{id}','PublisherController@publisherDetails')->name('publisher.details');
         Route::post('/publisher/update/{id}','PublisherController@publisherUpdate')->name('publisher.update');
         Route::get('/publisher/banned/all','PublisherController@allBannedPublisher')->name('publisher.banned.all');
         Route::get('/publisher/banned/{id}','PublisherController@publisherBanned')->name('publisher.banned');
         Route::get('/publisher/active/{id}','PublisherController@publisherActive')->name('publisher.active');
         Route::get('/publisher/email-unverified','PublisherController@emailUnverified')->name('publisher.email.unverified');
         Route::get('/publisher/sms-unverified','PublisherController@smsUnverified')->name('publisher.sms.unverified');
 
         Route::post('/publisher/ads/{slug}/{id}','PublisherController@publisherAds')->name('publisher.ads');
         Route::post('/publisher/ads/details/{id}','PublisherController@publisherAdsDetails')->name('publisher.ads.details');
         Route::post('publisher/add-sub-balance/{id}', 'PublisherController@addSubBalance')->name('publisher.addSubBalance');
         Route::get('publisher/login/history/{id}', 'PublisherController@loginHistory')->name('publisher.login.history.single');
 

core/app/Publisher.php
<?php


namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Publisher extends Authenticatable
{
    protected $guarded = [];
    protected $dates = ['created_at', 'updated_at', 'ver_code_send_at'];

    public function withdrawals()
    {
        return $this->hasMany(Withdrawal::class,'user_id')->where('status','!=',0);
    }
    public  function transactions()
    {
        return $this->hasMany(Transaction::class,'publisher_id')->orderBy('id','desc');
    }
    public function login_logs()
    {
        return $this->hasMany(UserLogin::class,'publisher_id');
    }

    public function ads()
    {
        return $this->belongsToMany(CreateAd::class,'publisher_ads','publisher_id','create_ad_id');
    }

    public function domain()
    {
        return $this->hasMany(DomainVerifcation::class);
    }

    public function tickets()
    {
        return $this->hasMany(SupportTicket::class,'publisher_id');
    }
    public function scopeEmailUnverified()
    {
        return $this->where('ev', 0);
    }

    public function scopeSmsUnverified()
    {
        return $this->where('sv', 0);
    }
    public function scopeBanned()
    {
        return $this->where('status', 2);
    }
    
}

core/app/Http/Controllers/Publisher/AdvertiseController.php
<?php

namespace App\Http\Controllers\Publisher;

use App\AdType;
use App\CreateAd;
use App\PublisherAd;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;


class AdvertiseController extends Controller
{
    public function advertises()
    {       
        $ads = AdType::all();
        $page_title = 'Advertise Types';
        $empty_message = 'No Advertise available';
        return view(activeTemplate().'publisher.advertises.advertises',compact('ads','page_title','empty_message'));
    }

    public function publishedAd()
    {
       $user = Auth::guard('publisher')->user();
       $page_title = 'Published Ads';
       $empty_message="No Published Ad";
       return view(activeTemplate().'publisher.advertises.published',compact('page_title','empty_message','user'));
    }

    public function details($id)
    {
        $page_title = 'Published Ad Details';
        $user = Auth::guard('publisher')->user();
        $advertise = CreateAd::findOrFail($id);
        $count = PublisherAd::where('publisher_id',$user->id)->where('create_ad_id',$advertise->id)->first();
        if($count==null){
            $notify[]=['error','Sorry Ad couldn\'t found'];
            return back()->withNotify($notify);
        }
        return view(activeTemplate().'publisher.advertises.details',compact('advertise','page_title','count'));
    }

}

core/resources/views/admin/publisher/all.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="row">
        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Name')</th>
                                <th scope="col">@lang('Email')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('Phone')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Actions')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($publishers as $publisher)
                            <tr>
                                <td data-label="@lang('Name')" class="text--primary">{{ $publisher->name }}</td>
                                <td data-label="@lang('Email')">{{ $publisher->email }}</td>
                                <td data-label="@lang('Username')">{{ $publisher->username }}</td>
                                <td data-label="@lang('Phone')">{{ $publisher->phone }}</td>
                                <td data-label="@lang('Status')"><span class="text--small badge font-weight-normal {{ $publisher->status==1?'badge--success':'badge--warning' }} ">{{ $publisher->status==1?'Active':'Banned' }}</span></td>
                                <td data-label="@lang('Actions')">
                                    <a href="{{ route('admin.publisher.details',['id'=>$publisher->id]) }}" class="icon-btn" data-toggle="tooltip" title="" data-original-title="@lang('Details')">
                                        <i class="las la-desktop text--shadow"></i>                 
                                    </a>
                                    
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
               <div class="card-footer py-4">
                   {{$publishers->links('admin.partials.paginate')}}
               </div>
            </div><!-- card end -->
        </div>
    </div>
@endsection

@push('breadcrumb-plugins')
    <form action="{{ route('admin.publisher.search') }}" method="GET" class="form-inline float-sm-right bg--white">
        <div class="input-group has_append">
            <input type="text" name="search" class="form-control" placeholder="@lang('Username or email')" value="{{ $search ?? '' }}">
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
@endpush

core/resources/views/admin/publisher/banned.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row">

        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Name')</th>
                                <th scope="col">@lang('Email')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('Phone')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Actions')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($publishers as $publisher)
                            <tr>
                                <td data-label="@lang('Name')" class="text--primary">{{ $publisher->name }}</td>
                                <td data-label="@lang('Email')">{{ $publisher->email }}</td>
                                <td data-label="@lang('Username')">{{ $publisher->username }}</td>
                                <td data-label="@lang('Phone')">{{ $publisher->phone }}</td>
                                <td data-label="@lang('Status')"><span class="text--small badge font-weight-normal {{ $publisher->status==1?'badge--success':'badge--warning' }} ">{{ $publisher->status==1?'Active':'Banned' }}</span></td>
                                <td data-label="@lang('Actions')">
                                    <a href="{{ route('admin.publisher.active',['id'=>$publisher->id]) }}" class="icon-btn btn--success mr-2" data-toggle="tooltip" data-original-title="@lang('make active')">
                                        <i class="las la-check-double text--shadow"></i>               
                                    </a>
                                    <a href="{{ route('admin.publisher.details',['id'=>$publisher->id]) }}" class="icon-btn" data-toggle="tooltip" title="" data-original-title="Details">
                                        <i class="las la-desktop text--shadow"></i>                 
                                    </a>
                                    
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{$publishers->links('admin.partials.paginate')}}
                </div>
            </div><!-- card end -->
        </div>


    </div>
@endsection

core/resources/views/admin/publisher/emailUnverified.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row">

        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Name')</th>
                                <th scope="col">@lang('Email')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('Phone')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Actions')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($publishers as $publisher)
                            <tr>
                                <td data-label="@lang('Name')" class="text--primary">{{ $publisher->name }}</td>
                                <td data-label="@lang('Email')">{{ $publisher->email }}</td>
                                <td data-label="@lang('Username')">{{ $publisher->username }}</td>
                                <td data-label="@lang('Phone')">{{ $publisher->phone }}</td>
                                <td data-label="@lang('Status')"><span class="text--small badge font-weight-normal {{ $publisher->status==1?'badge--success':'badge--warning' }} ">{{ $publisher->status==1?'Active':'Banned' }}</span></td>
                                <td data-label="@lang('Actions')">
                                   
                                    <a href="{{ route('admin.publisher.details',['id'=>$publisher->id]) }}" class="icon-btn" data-toggle="tooltip" title="" data-original-title="Details">
                                        <i class="las la-desktop text--shadow"></i>                 
                                    </a>
                                    
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{$publishers->links('admin.partials.paginate')}}
                </div>
            </div><!-- card end -->
        </div>


    </div>
@endsection

core/resources/views/admin/publisher/email_all.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row mb-none-30">
        <div class="col-xl-12">
            <div class="card">
                <form action="{{ route('admin.publisher.email.all') }}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label class="font-weight-bold">@lang('Subject') <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" placeholder="Email subject" name="subject"  required/>
                            </div>
                            <div class="form-group col-md-12">
                                <label class="font-weight-bold">@lang('Message') <span class="text-danger">*</span></label>
                                <textarea name="message" rows="10" class="form-control nicEdit" placeholder="Your message"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="form-row">
                            <div class="form-group col-md-12 text-center">
                                <button type="submit" class="btn btn-block btn--primary mr-2">@lang('Send Email')</button>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

@endsection

core/resources/views/admin/publisher/logins.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="row">

        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">

                    <div class="table-responsive--sm table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Date')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('IP')</th>
                                <th scope="col">@lang('Location')</th>
                                <th scope="col">@lang('Browser')</th>
                                <th scope="col">@lang('OS')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($login_logs as $log)
                                <tr>
                                    <td data-label="@lang('Date')">{{ \Carbon\Carbon::parse($log->created_at)->diffForHumans() }}</td>
                                    <td data-label="@lang('Username')"><a href="{{ route('admin.publisher.details', $log->publisher_id)}}"> {{ ($log->publisher) ? $log->publisher->username : '' }}</a></td>
                                    <td data-label="@lang('IP')">
                                        <a href="{{route('admin.users.login.ipHistory',[$log->user_ip])}}">
                                            {{ $log->user_ip }}
                                        </a>
                                    </td>
                                    <td data-label="@lang('Location')">{{ $log->location }}</td>
                                    <td data-label="@lang('Browser')">{{ $log->browser }}</td>
                                    <td data-label="@lang('OS')">{{ $log->os }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{ $login_logs->links('admin.partials.paginate') }}
                </div>
            </div><!-- card end -->
        </div>


    </div>
@endsection



@push('breadcrumb-plugins')
    @if(request()->routeIs('admin.users.login.history'))
    <form action="{{ route('admin.users.login.history') }}" method="GET" class="form-inline float-sm-right bg--white">
        <div class="input-group has_append">
            <input type="text" name="search" class="form-control" placeholder="Username" value="{{ $search ?? '' }}">
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
    @endif
@endpush

core/resources/views/admin/publisher/smsUnverified.blade.php
@extends('admin.layouts.app')

@section('panel')

    <div class="row">

        <div class="col-lg-12">
            <div class="card b-radius--10 ">
                <div class="card-body p-0">
                    <div class="table-responsive--md  table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Name')</th>
                                <th scope="col">@lang('Email')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('Phone')</th>
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Actions')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($publishers as $publisher)
                            <tr>
                                <td data-label="@lang('Name')" class="text--primary">{{ $publisher->name }}</td>
                                <td data-label="@lang('Email')">{{ $publisher->email }}</td>
                                <td data-label="@lang('Username')">{{ $publisher->username }}</td>
                                <td data-label="@lang('Phone')">{{ $publisher->phone }}</td>
                                <td data-label="@lang('Status')"><span class="text--small badge font-weight-normal {{ $publisher->status==1?'badge--success':'badge--warning' }} ">{{ $publisher->status==1?'Active':'Banned' }}</span></td>
                                <td data-label="@lang('Actions')">
                                    
                                    <a href="{{ route('admin.publisher.details',['id'=>$publisher->id]) }}" class="icon-btn" data-toggle="tooltip" title="" data-original-title="Details">
                                        <i class="las la-desktop text--shadow"></i>                 
                                    </a>
                                    
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $empty_message }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{$publishers->links('admin.partials.paginate')}}
                </div>
            </div><!-- card end -->
        </div>


    </div>
@endsection